-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "role" "Role" NOT NULL DEFAULT E'USER',
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
